const getItems = () => {
  return [
    {
      id: "showLogin",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
    {
      id: "showLogin1",
      desc: "should display the login",
      defaultValue: true,
      value: true,
      type: "bool",
    },
  ];
};

const getProperties = () => {
  return new Promise((resolved, rejected) => {
    setTimeout(() => {
      resolved(getItems());
    }, 3000);
  });
};

export { getProperties };
